# wrangler.toml (wrangler v3.79.0^)

name = "4fwd-co"
main = "./js/worker.js"
compatibility_date = "2024-10-26"

assets = { directory = "./", binding = "ASSETS" }
kv_namespaces = [
  { binding = "LINKS", id = "b8607ecba5084700a6cddf90bcd1dd08" }
]

[observability]
enabled = true
head_sampling_rate = 1
